FROM public.ecr.aws/lambda/python:3.9

# ワークディレクトリを設定
WORKDIR ${LAMBDA_TASK_ROOT}

# 必要なファイルをコピー
COPY lambda_function/* ./

# 必要なディレクトリをコピー
COPY lambda_function/chains ./chains/
COPY lambda_function/prompts ./prompts/
COPY lambda_function/registry ./registry/
COPY lambda_function/snippets ./snippets/

# 必要なライブラリをインストール
RUN pip install --no-cache-dir -r requirements.txt

# Lambda関数ハンドラの設定
CMD [ "lambda_function.lambda_handler" ]
